from __future__ import annotations

from datetime import datetime
from typing import Protocol

from sanitized_data_platform.domain.entities import (
    AuditEvent,
    BaselineRefreshJob,
    BaselineRefreshSchedule,
    DataSource,
    DatasetProfile,
    ExtractionArtifact,
    ExtractionJob,
    ExtractionPlan,
    ExtractionPlanSnapshot,
    LineageRecord,
    MetadataObject,
    PublishJob,
    Relationship,
    SanitizedBaseline,
    SensitivityTag,
    System,
    TargetEnvironment,
    TransformationPolicy,
    ValidationReport,
)
from sanitized_data_platform.domain.enums import MetadataObjectType


class ClockPort(Protocol):
    def now(self) -> datetime: ...


class IdGeneratorPort(Protocol):
    def new_id(self, prefix: str) -> str: ...


class SystemRepository(Protocol):
    def list_active(self) -> list[System]: ...
    def get_by_id(self, system_id: str) -> System | None: ...


class DataSourceRepository(Protocol):
    def list_active(self) -> list[DataSource]: ...
    def get_by_id(self, source_id: str) -> DataSource | None: ...
    def get_active_by_system_id(self, system_id: str) -> DataSource | None: ...


class TargetEnvironmentRepository(Protocol):
    def list_active(self) -> list[TargetEnvironment]: ...
    def get_by_id(self, environment_id: str) -> TargetEnvironment | None: ...


class DatasetProfileRepository(Protocol):
    def list_active(self) -> list[DatasetProfile]: ...
    def get_by_id(self, profile_id: str) -> DatasetProfile | None: ...


class BaselineRepository(Protocol):
    def list_active_for_system(self, system_id: str) -> list[SanitizedBaseline]: ...
    def list_for_system(self, system_id: str) -> list[SanitizedBaseline]: ...
    def get_by_id(self, baseline_id: str) -> SanitizedBaseline | None: ...
    def add(self, baseline: SanitizedBaseline) -> None: ...
    def save(self, baseline: SanitizedBaseline) -> None: ...


class ValidationRepository(Protocol):
    def get_latest_for_baseline(self, baseline_id: str) -> ValidationReport | None: ...


class MetadataCatalogRepository(Protocol):
    def list_objects(
        self,
        source_id: str,
        *,
        object_type: MetadataObjectType | None = None,
    ) -> list[MetadataObject]: ...
    def upsert_objects(self, objects: list[MetadataObject]) -> None: ...
    def upsert_relationships(self, relationships: list[Relationship]) -> None: ...
    def list_relationships(self, source_id: str) -> list[Relationship]: ...


class SourceMetadataDiscoveryPort(Protocol):
    def list_schemas(self, source: DataSource) -> list[MetadataObject]: ...
    def list_tables(self, source: DataSource) -> list[MetadataObject]: ...
    def list_columns(self, source: DataSource) -> list[MetadataObject]: ...
    def list_relationships(self, source: DataSource) -> list[Relationship]: ...


class TransformationPolicyRepository(Protocol):
    def list_active_for_system(self, system_id: str) -> list[TransformationPolicy]: ...


class ClassificationRepository(Protocol):
    def list_sensitivity_tags(self, source_id: str) -> list[SensitivityTag]: ...


class PublishJobRepository(Protocol):
    def add(self, job: PublishJob) -> None: ...
    def get_by_id(self, job_id: str) -> PublishJob | None: ...
    def save(self, job: PublishJob) -> None: ...


class BaselineRefreshJobRepository(Protocol):
    def add(self, job: BaselineRefreshJob) -> None: ...
    def get_by_id(self, job_id: str) -> BaselineRefreshJob | None: ...
    def list_all(self) -> list[BaselineRefreshJob]: ...
    def save(self, job: BaselineRefreshJob) -> None: ...


class BaselineRefreshScheduleRepository(Protocol):
    def add(self, schedule: BaselineRefreshSchedule) -> None: ...
    def get_by_id(self, schedule_id: str) -> BaselineRefreshSchedule | None: ...
    def list_all(self) -> list[BaselineRefreshSchedule]: ...
    def list_enabled(self) -> list[BaselineRefreshSchedule]: ...
    def save(self, schedule: BaselineRefreshSchedule) -> None: ...


class ExtractionJobRepository(Protocol):
    def add(self, job: ExtractionJob) -> None: ...
    def get_by_id(self, job_id: str) -> ExtractionJob | None: ...
    def list_all(self) -> list[ExtractionJob]: ...
    def save(self, job: ExtractionJob) -> None: ...


class ExtractionPlanSnapshotRepository(Protocol):
    def add(self, snapshot: ExtractionPlanSnapshot) -> None: ...
    def get_by_id(self, snapshot_id: str) -> ExtractionPlanSnapshot | None: ...


class ExtractionArtifactRepository(Protocol):
    def add(self, artifact: ExtractionArtifact) -> None: ...
    def get_by_id(self, artifact_id: str) -> ExtractionArtifact | None: ...
    def get_by_job_id(self, job_id: str) -> ExtractionArtifact | None: ...
    def list_all(self) -> list[ExtractionArtifact]: ...
    def save(self, artifact: ExtractionArtifact) -> None: ...


class AuditEventRepository(Protocol):
    def add(self, event: AuditEvent) -> None: ...
    def list_for_subject(self, subject_id: str) -> list[AuditEvent]: ...


class LineageRepository(Protocol):
    def add(self, record: LineageRecord) -> None: ...
    def list_related(self, *, reference_type: str, reference_id: str) -> list[LineageRecord]: ...


class JobQueuePort(Protocol):
    def enqueue(self, job_id: str) -> None: ...
    def dequeue(self) -> str | None: ...


class BaselineRefreshQueuePort(Protocol):
    def enqueue(self, job_id: str) -> None: ...
    def dequeue(self) -> str | None: ...


class ExtractionQueuePort(Protocol):
    def enqueue(self, job_id: str) -> None: ...
    def dequeue(self) -> str | None: ...


class PolicyPort(Protocol):
    def assert_publish_allowed(
        self,
        *,
        source: DataSource,
        target: TargetEnvironment,
        profile: DatasetProfile,
        requested_by: str,
    ) -> None: ...


class PublishPipelinePort(Protocol):
    def execute(
        self,
        *,
        job: PublishJob,
        source: DataSource,
        baseline: SanitizedBaseline | None,
        target: TargetEnvironment,
        profile: DatasetProfile,
    ) -> dict[str, object]: ...


class BaselineRefreshPipelinePort(Protocol):
    def execute(
        self,
        *,
        job: BaselineRefreshJob,
        source: DataSource,
        profile: DatasetProfile,
        existing_baseline: SanitizedBaseline | None,
    ) -> dict[str, object]: ...


class ExtractionPipelinePort(Protocol):
    def execute(
        self,
        *,
        job: ExtractionJob,
        plan: ExtractionPlan,
    ) -> dict[str, object]: ...
